# Generated by Django 5.2.6 on 2025-09-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(upload_to='about/hero/')),
                ('overlay_title', models.CharField(help_text='Big centered title on the hero', max_length=200)),
                ('overlay_text', models.CharField(blank=True, help_text='Small line(s) under title in overlay', max_length=400)),
                ('body_text', models.TextField(help_text='Long content that appears in the green block below the hero')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this about entry (admin chooses which to show)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
