# Generated by Django 5.2.6 on 2025-09-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petproducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petproduct',
            options={'ordering': ['order', '-created', 'id']},
        ),
    ]
