# Generated by Django 5.2.6 on 2025-09-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petproducts', '0003_alter_productreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
