# Generated by Django 5.2.6 on 2025-09-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetServiceLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='petservices/banner/')),
                ('logo', models.ImageField(upload_to='petservices/logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
