# Generated by Django 5.2.6 on 2025-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petservices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petservicelanding',
            name='banner',
        ),
        migrations.AddField(
            model_name='petservicelanding',
            name='left_banner',
            field=models.ImageField(blank=True, null=True, upload_to='petservices/banner_left/'),
        ),
        migrations.AddField(
            model_name='petservicelanding',
            name='right_banner',
            field=models.ImageField(blank=True, null=True, upload_to='petservices/banner_right/'),
        ),
        migrations.AlterField(
            model_name='petservicelanding',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='petservices/logo/'),
        ),
    ]
