# Generated by Django 5.2.6 on 2025-09-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petservices', '0002_remove_petservicelanding_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Pet Services', max_length=200)),
                ('intro_text', models.TextField(blank=True)),
                ('customer_service_title', models.CharField(default='customer service', max_length=80)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('promo_left_title', models.CharField(blank=True, max_length=120)),
                ('promo_left_subtitle', models.TextField(blank=True)),
                ('promo_left_button', models.CharField(blank=True, max_length=40)),
                ('center_image', models.ImageField(blank=True, null=True, upload_to='petservices/center/')),
                ('promo_right_title', models.CharField(blank=True, max_length=120)),
                ('promo_right_text', models.TextField(blank=True)),
                ('promo_right_button', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='petservices.petservicespage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
