# Generated by Django 5.2.6 on 2025-09-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petservices', '0003_petservicespage_servicecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_image', models.ImageField(upload_to='consult/cta_top/')),
                ('cta_text', models.CharField(max_length=255)),
                ('cta_button_text', models.CharField(default='Consult Now', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_image', models.ImageField(upload_to='consult/left/')),
                ('right_image', models.ImageField(upload_to='consult/right/')),
                ('overlay_title', models.CharField(blank=True, max_length=255)),
                ('overlay_text', models.TextField(blank=True)),
                ('overlay_cta_text', models.CharField(default='Consult Now', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='consult/icons/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VetDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_title', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(upload_to='consult/doctors/')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
