# Generated by Django 5.2.6 on 2025-09-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petservices', '0004_consultcta_consulthero_serviceicon_vetdoctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='consult/banner/')),
                ('overlay_title', models.CharField(blank=True, max_length=255)),
                ('overlay_text', models.TextField(blank=True)),
                ('overlay_cta_text', models.CharField(blank=True, default='Consult Now', max_length=100)),
                ('cta_top_image', models.ImageField(blank=True, null=True, upload_to='consult/cta_top/')),
                ('cta_text', models.CharField(blank=True, max_length=255)),
                ('cta_button_text', models.CharField(blank=True, default='Consult Now', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ConsultCTA',
        ),
        migrations.DeleteModel(
            name='ConsultHero',
        ),
        migrations.DeleteModel(
            name='ServiceIcon',
        ),
    ]
