# Generated by Django 5.2.6 on 2025-09-25 19:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petservices', '0005_consultpage_delete_consultcta_delete_consulthero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='booking/banner/')),
                ('feature_1', models.CharField(blank=True, default='Pay & book the consultant', max_length=120)),
                ('feature_2', models.CharField(blank=True, default='Choose video or Teleconsultation', max_length=120)),
                ('feature_3', models.CharField(blank=True, default='Receive prescription after the call', max_length=120)),
                ('overlay_title', models.CharField(blank=True, default='Instant and complete vet care', max_length=255)),
                ('overlay_text', models.TextField(blank=True, default='Wherever you are. At only 299, get end-to-end support from our vets.')),
                ('overlay_cta_text', models.CharField(blank=True, default='Consult Now', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('299.00'), max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, default=Decimal('499.00'), max_digits=10)),
                ('discount_text', models.CharField(blank=True, default='40% OFF', max_length=100)),
                ('offers_text', models.CharField(blank=True, default='Bank offers and coupons', max_length=255)),
                ('offers_button_text', models.CharField(blank=True, default='Check offers', max_length=80)),
                ('cod_info', models.CharField(blank=True, default='Currently, cash on delivery is not available on this product.', max_length=255)),
                ('delivery_info', models.CharField(blank=True, default='Free delivery on orders above ₹599', max_length=255)),
                ('add_to_cart_text', models.CharField(blank=True, default='Add to cart', max_length=80)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
