# Generated by Django 5.2.6 on 2025-09-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='banners/')),
                ('bg_color', models.CharField(default='#e0ffee', max_length=20)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('overlay', models.CharField(choices=[('none', 'None'), ('rain', 'Rain + Lightning'), ('shape', 'Decorative Shape')], default='none', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
