# Generated by Django 5.2.6 on 2025-09-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slideritem_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='pet_categories/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SliderItem',
        ),
    ]
