# Generated by Django 5.2.6 on 2025-09-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_petcategory_delete_slideritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Shop & Save', max_length=50)),
                ('discount_text', models.CharField(default='Save 35%', max_length=50)),
                ('image', models.ImageField(upload_to='promo_banners/')),
                ('link', models.URLField(blank=True, help_text='Optional button link')),
            ],
        ),
    ]
