# Generated by Django 5.2.6 on 2025-09-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_promobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promobanner',
            name='link',
            field=models.CharField(blank=True, help_text='Enter a relative path like /category/dog or a full URL like https://example.com', max_length=255),
        ),
    ]
