# Generated by Django 5.2.6 on 2025-09-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_promobanner_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferStrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('product_image', models.ImageField(upload_to='offer_strip/')),
                ('button_text', models.CharField(default='Shop Now', max_length=64)),
                ('link', models.CharField(blank=True, help_text='Internal path or external URL', max_length=255)),
                ('background_color', models.CharField(default='#9fffae', max_length=20)),
                ('text_color', models.CharField(default='#000000', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
