# Generated by Django 5.2.6 on 2025-09-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_offerstrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('promo_text', models.CharField(blank=True, help_text='Short promo shown below the card', max_length=160)),
                ('image', models.ImageField(upload_to='pet_services/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
