# Generated by Django 5.2.6 on 2025-09-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_petservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarousalBanner1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text', models.CharField(default='Shop Now', max_length=100)),
                ('link', models.URLField(blank=True, help_text='Full URL or relative path', null=True)),
                ('image', models.ImageField(help_text='Left side image', upload_to='banners/')),
                ('right_image', models.ImageField(blank=True, help_text='Right side illustration (e.g. umbrella)', null=True, upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousal Banner',
                'verbose_name_plural': 'Carousal Banners',
                'db_table': 'carousal_banner1',
            },
        ),
    ]
