# Generated by Django 5.2.6 on 2025-09-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_carousalbanner1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarousalBanner2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_image', models.ImageField(blank=True, null=True, upload_to='banners/carousal2/left/')),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='banners/carousal2/right/')),
                ('ribbon_text', models.CharField(blank=True, max_length=255)),
                ('overlay_title', models.TextField(blank=True)),
                ('overlay_body', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=128)),
                ('button_link', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower first)')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel Banner 2',
                'verbose_name_plural': 'Carousel Banner 2',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
