# Generated by Django 5.2.6 on 2025-09-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_carousalbanner2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarousalBanner3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_image_1', models.ImageField(blank=True, null=True, upload_to='banners/carousal3/left/')),
                ('left_image_2', models.ImageField(blank=True, null=True, upload_to='banners/carousal3/left/')),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='banners/carousal3/right/')),
                ('diamond_text', models.CharField(blank=True, help_text='Text shown in the diamond price tag (can include newline)', max_length=255)),
                ('save_text', models.CharField(blank=True, help_text='Small save pill text', max_length=128)),
                ('button_text', models.CharField(blank=True, max_length=128)),
                ('button_link', models.CharField(blank=True, max_length=512)),
                ('bg_color', models.CharField(blank=True, default='#98FB98', help_text='Optional hex color for left background', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel Banner 3',
                'verbose_name_plural': 'Carousel Banner 3',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
