# Generated by Django 5.2.6 on 2025-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_carousalbanner3'),
        ('petproducts', '0002_alter_petproduct_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalmingBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=512)),
                ('image', models.ImageField(blank=True, null=True, upload_to='calming_banners/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calming Banner',
                'verbose_name_plural': 'Calming Banners',
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CalmingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Top Rated Calming Products', max_length=255)),
                ('items_per_page', models.PositiveIntegerField(default=4)),
                ('limit', models.PositiveIntegerField(default=12)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='calming_sections', to='petproducts.petproduct')),
            ],
            options={
                'verbose_name': 'Calming Section',
                'verbose_name_plural': 'Calming Sections',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
