# Generated by Django 5.2.6 on 2025-09-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_calmingbanner_calmingsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalmingBanner',
        ),
        migrations.DeleteModel(
            name='CalmingSection',
        ),
    ]
