# Generated by Django 5.2.6 on 2025-09-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_calmingbanner_delete_calmingsection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetCategory',
            new_name='HomeCategory',
        ),
    ]
