# Generated by Django 5.2.6 on 2025-09-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('content', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Mega Menu',
                'verbose_name_plural': 'Mega Menus',
            },
        ),
    ]
