# Generated by Django 5.2.6 on 2025-09-24 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_megamenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megamenu',
            name='content',
        ),
        migrations.CreateModel(
            name='MegaMenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.megamenu')),
            ],
            options={
                'verbose_name': 'Mega Menu Section',
                'verbose_name_plural': 'Mega Menu Sections',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MegaMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('path', models.CharField(blank=True, help_text='URL or route', max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.megamenusection')),
            ],
            options={
                'verbose_name': 'Mega Menu Item',
                'verbose_name_plural': 'Mega Menu Items',
                'ordering': ['id'],
            },
        ),
    ]
