# Generated by Django 5.2.6 on 2025-09-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_megamenu_content_megamenusection_megamenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='megamenu',
            name='path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
