# Generated by Django 5.2.6 on 2025-09-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_megamenu_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='megamenusection',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
