# Generated by Django 5.2.6 on 2025-09-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_megamenusection_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megamenu',
            name='path',
        ),
    ]
