# Generated by Django 5.2.6 on 2025-09-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sitesettings_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megamenusection',
            name='menu',
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
        migrations.AddField(
            model_name='megamenu',
            name='content',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='MegaMenuItem',
        ),
        migrations.DeleteModel(
            name='MegaMenuSection',
        ),
    ]
