# Generated by Django 5.2.6 on 2025-09-24 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_megamenusection_menu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='megamenu',
            options={'ordering': ['order', 'title']},
        ),
        migrations.RemoveField(
            model_name='megamenu',
            name='content',
        ),
        migrations.RemoveField(
            model_name='megamenu',
            name='label',
        ),
        migrations.AddField(
            model_name='megamenu',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='megamenu',
            name='title',
            field=models.CharField(default='Untitled Menu', max_length=200),
        ),
        migrations.AddField(
            model_name='megamenu',
            name='title_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='megamenu',
            name='key',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='MegaMenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Menu', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mega_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.megamenu')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MegaMenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.megamenusection')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
