# Generated by Django 5.2.6 on 2025-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_megamenu_options_remove_megamenu_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='megamenusection',
            name='path',
            field=models.CharField(blank=True, help_text='Optional URL for this section', max_length=300),
        ),
        migrations.AlterField(
            model_name='megamenusection',
            name='title',
            field=models.CharField(help_text='Section title', max_length=200),
        ),
    ]
