# Generated by Django 5.2.6 on 2025-09-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_megamenusection_path_alter_megamenusection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='megamenu',
            name='left_image',
            field=models.ImageField(blank=True, null=True, upload_to='mega_menu_images/'),
        ),
        migrations.AddField(
            model_name='megamenu',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to='mega_menu_images/'),
        ),
    ]
