# Generated by Django 5.2.6 on 2025-09-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_megamenu_left_image_megamenu_right_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMenuBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='mega_menu_brands/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('mega_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='core.megamenu')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
