# Generated by Django 5.2.6 on 2025-09-25 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_megamenubrand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
    ]
